export const SMALLCHANGE = 'SMALLCHANGE';
export const MEDIUMCHANGE = 'MEDIUMCHANGE';
export const LARGECHANGE = 'LARGECHANGE';
export const BOXCHANGE = 'BOXCHANGE';

export const SMALLINCREMENT = 'SMALLINCREMENT';
export const MEDIUMINCREMENT = 'MEDIUMINCREMENT';
export const LARGEINCREMENT = 'LARGEINCREMENT';
export const BOXINCREMENT = 'BOXINCREMENT';

export const SMALLDECREMENT = 'SMALLDECREMENT';
export const MEDIUMDECREMENT = 'MEDIUMDECREMENT';
export const LARGEDECREMENT = 'LARGEDECREMENT';
export const BOXDECREMENT = 'BOXDECREMENT';

export const BOXESCOUNT = 'BOXESCOUNT';
